Replace Exoscale compute endpoint /compute by /v1
exoscale/terraform-provider-exoscale pull request #27
Opened 2019-12-03 17:49 UTC by pierre-emmanuelJ

Replace Exoscale compute endpoint /compute by /v1

2019-12-05 08:46 UTC, falzm approved these changes

2019-12-06 08:53 UTC, falzm requested changes
We're grown-ups now, let's switch to `.com` for the API endpoints 😉

2019-12-06 08:53 UTC, falzm commented on exoscale/client.go
> +const defaultComputeEndpoint = "https://api.exoscale.ch/v1"
```suggestion
const defaultComputeEndpoint = "https://api.exoscale.com/v1"
```

2019-12-06 08:53 UTC, falzm commented on exoscale/client.go
>  const defaultDNSEndpoint = "https://api.exoscale.ch/dns"
```suggestion
const defaultDNSEndpoint = "https://api.exoscale.com/dns"
```

2019-12-09 17:11 UTC, pierre-emmanuelJ commented on exoscale/client.go
> +const defaultComputeEndpoint = "https://api.exoscale.ch/v1"
Nice catch

2019-12-10 07:25 UTC, falzm approved these changes

2019-12-10 10:06 UTC, illi-j approved these changes
🎂

2019-12-10 13:27 UTC, merged