healthcheck: prepare the upcoming TLS checks for managed eips
exoscale/terraform-provider-exoscale pull request #66
Opened 2020-08-21 13:45 UTC by pyr

2020-08-24 06:42 UTC, falzm commented
@pyr are those new attributes editable with existing EIPs? If so, you'll also have to change state change in `resourceIPAddressUpdate()` (see https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/resource_exoscale_ipaddress.go#L297-L335)

2020-08-24 06:43 UTC, falzm requested changes
A typo to fix and possibly missing update-related code.

2020-08-24 06:43 UTC, falzm commented on exoscale/resource_exoscale_ipaddress.go
> +			return errors.New("healthcheck_path must be specified in \"http\" or \"htts\" mode")
```suggestion
			return errors.New("healthcheck_path must be specified in \"http\" or \"https\" mode")
```

2020-08-24 07:30 UTC, falzm commented
You should rebase your branch on the `master` branch which has been updated to fix the failing CI tests.

2020-08-24 08:01 UTC, pierre-emmanuelJ approved these changes
Could be nice to add a test for it ;)

2020-08-24 09:30 UTC, pyr commented
waiting for exoscale/egoscale#444

2020-08-24 09:39 UTC, pyr commented
> Could be nice to add a test for it ;)

What behavior would you add tests for in this case?

2020-08-24 09:44 UTC, falzm commented
> What behavior would you add tests for in this case?

That the new parameters are correctly updated upon configuration change (e.g. set `healthcheck_skip_tls_verify = true` and `healthcheck_skip_tls_sni = "example.net"`: https://github.com/exoscale/terraform-provider-exoscale/blob/master/exoscale/resource_exoscale_ipaddress_test.go#L55-L66

2020-08-25 15:41 UTC, pyr commented
I added tests as requested. As soon as the functionality is live they should now pass. Thanks for the help!

2020-09-01 15:35 UTC, falzm approved these changes
Needed a few fixes here and there, looks ready now 👍

2020-09-01 15:38 UTC, merged